# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-20 01:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sp2011',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Term', models.TextField()),
                ('Subject', models.TextField()),
                ('Catalog', models.TextField()),
                ('Section', models.TextField()),
                ('Title', models.TextField()),
                ('A', models.IntegerField(default=0)),
                ('Aminus', models.IntegerField(default=0)),
                ('Bplus', models.IntegerField(default=0)),
                ('B', models.IntegerField(default=0)),
                ('Bminus', models.IntegerField(default=0)),
                ('Cplus', models.IntegerField(default=0)),
                ('C', models.IntegerField(default=0)),
                ('P', models.IntegerField(default=0)),
                ('S', models.IntegerField(default=0)),
                ('D', models.IntegerField(default=0)),
                ('F', models.IntegerField(default=0)),
                ('U', models.IntegerField(default=0)),
                ('I', models.IntegerField(default=0)),
                ('IP', models.IntegerField(default=0)),
                ('W', models.IntegerField(default=0)),
                ('Total_Grades', models.IntegerField(default=0)),
                ('Avg_Grade_in_Grade_Points', models.IntegerField(default=0)),
                ('Primary_Instructor', models.TextField()),
            ],
        ),
    ]
