# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-20 04:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sp2011',
            name='Avg_Grade_in_Grade_Points',
            field=models.FloatField(default=0),
        ),
    ]
